import type {
  DestinationCountry,
  ImmigrationPathway,
  MigrationGoal,
} from "@/lib/types";

export const migrationGoalLabels: Record<MigrationGoal, string> = {
  study: "Study route",
  work: "Skilled work",
  family: "Family resettlement",
  investment: "Investment",
  passport: "Stronger passport",
  fast_pr: "Fast PR",
  low_cost: "Lower cost",
};

export const originCountries = [
  "India",
  "Indonesia",
  "Malaysia",
  "Philippines",
  "Singapore",
  "United Arab Emirates",
  "United States",
  "United Kingdom",
];

export const destinationCountries: DestinationCountry[] = [
  {
    id: "canada",
    iso2: "CA",
    name: "Canada",
    region: "North America",
    longitude: -106.3468,
    latitude: 56.1304,
    passportStrength: "very_strong",
    costLevel: "high",
    officialImmigrationUrl: "https://www.canada.ca/en/immigration-refugees-citizenship.html",
  },
  {
    id: "australia",
    iso2: "AU",
    name: "Australia",
    region: "Oceania",
    longitude: 133.7751,
    latitude: -25.2744,
    passportStrength: "very_strong",
    costLevel: "very_high",
    officialImmigrationUrl: "https://immi.homeaffairs.gov.au/",
  },
  {
    id: "new-zealand",
    iso2: "NZ",
    name: "New Zealand",
    region: "Oceania",
    longitude: 174.886,
    latitude: -40.9006,
    passportStrength: "very_strong",
    costLevel: "high",
    officialImmigrationUrl: "https://www.immigration.govt.nz/",
  },
  {
    id: "ireland",
    iso2: "IE",
    name: "Ireland",
    region: "Europe",
    longitude: -8.2439,
    latitude: 53.4129,
    passportStrength: "very_strong",
    costLevel: "high",
    officialImmigrationUrl: "https://www.irishimmigration.ie/",
  },
  {
    id: "united-kingdom",
    iso2: "GB",
    name: "United Kingdom",
    region: "Europe",
    longitude: -3.436,
    latitude: 55.3781,
    passportStrength: "very_strong",
    costLevel: "very_high",
    officialImmigrationUrl: "https://www.gov.uk/browse/visas-immigration",
  },
  {
    id: "germany",
    iso2: "DE",
    name: "Germany",
    region: "Europe",
    longitude: 10.4515,
    latitude: 51.1657,
    passportStrength: "exceptional",
    costLevel: "medium",
    officialImmigrationUrl: "https://www.make-it-in-germany.com/en/",
  },
  {
    id: "united-states",
    iso2: "US",
    name: "United States",
    region: "North America",
    longitude: -95.7129,
    latitude: 37.0902,
    passportStrength: "very_strong",
    costLevel: "very_high",
    officialImmigrationUrl: "https://www.uscis.gov/",
  },
  {
    id: "malta",
    iso2: "MT",
    name: "Malta",
    region: "Europe",
    longitude: 14.3754,
    latitude: 35.9375,
    passportStrength: "very_strong",
    costLevel: "medium",
    officialImmigrationUrl: "https://identita.gov.mt/",
  },
];

export const immigrationPathways: ImmigrationPathway[] = [
  {
    id: "ca-express-entry",
    countryId: "canada",
    name: "Express Entry",
    category: "skilled_worker",
    summary: "Points-based permanent residence route for skilled workers.",
    prTimelineMonths: [6, 18],
    citizenshipTimelineYears: [4, 6],
    minSavingsUsd: 10500,
    minEducationLevel: "bachelors",
    minLanguageLevel: "advanced",
    idealAgeMax: 35,
    familyFriendly: true,
    documents: ["Passport", "Language test", "Education credential assessment", "Proof of funds", "Work reference letters", "Police certificates", "Medical exam"],
    eligibilityNotes: ["Competitive CRS score is required.", "Occupation and language scores can strongly affect ranking."],
    sourceLinks: [{ title: "Express Entry", url: "https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry.html", publisher: "Government of Canada" }],
    lastReviewed: "2026-04-25",
    confidence: "seeded",
  },
  {
    id: "ca-study-pgwp",
    countryId: "canada",
    name: "Study Permit to PGWP to PR",
    category: "study_to_pr",
    summary: "Study in Canada, gain Canadian work experience, then apply for PR.",
    prTimelineMonths: [36, 60],
    citizenshipTimelineYears: [5, 8],
    minSavingsUsd: 30000,
    minEducationLevel: "secondary",
    minLanguageLevel: "intermediate",
    idealAgeMax: null,
    familyFriendly: true,
    documents: ["Passport", "Letter of acceptance", "Proof of funds", "Study plan", "Academic transcripts", "Language test"],
    eligibilityNotes: ["Institution and program choices matter for post-graduation work eligibility."],
    sourceLinks: [{ title: "Study permit", url: "https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada.html", publisher: "Government of Canada" }],
    lastReviewed: "2026-04-25",
    confidence: "seeded",
  },
  {
    id: "au-skilled-189",
    countryId: "australia",
    name: "Skilled Independent visa subclass 189",
    category: "skilled_worker",
    summary: "Invitation-based PR route for skilled workers in eligible occupations.",
    prTimelineMonths: [12, 30],
    citizenshipTimelineYears: [5, 7],
    minSavingsUsd: 15000,
    minEducationLevel: "bachelors",
    minLanguageLevel: "advanced",
    idealAgeMax: 45,
    familyFriendly: true,
    documents: ["Passport", "Skills assessment", "English test", "Employment evidence", "Police certificates", "Health examination"],
    eligibilityNotes: ["Requires points test, eligible occupation, and invitation."],
    sourceLinks: [{ title: "Skilled Independent visa", url: "https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-independent-189", publisher: "Australian Department of Home Affairs" }],
    lastReviewed: "2026-04-25",
    confidence: "seeded",
  },
  {
    id: "nz-skilled-migrant",
    countryId: "new-zealand",
    name: "Skilled Migrant Category",
    category: "skilled_worker",
    summary: "Residence pathway for skilled workers with qualifying employment or offers.",
    prTimelineMonths: [12, 30],
    citizenshipTimelineYears: [6, 8],
    minSavingsUsd: 12000,
    minEducationLevel: "bachelors",
    minLanguageLevel: "advanced",
    idealAgeMax: 55,
    familyFriendly: true,
    documents: ["Passport", "Job offer or employment evidence", "Qualification evidence", "English evidence", "Police certificates", "Medical certificates"],
    eligibilityNotes: ["A New Zealand skilled job or offer is typically central."],
    sourceLinks: [{ title: "Skilled Migrant Category Resident Visa", url: "https://www.immigration.govt.nz/new-zealand-visas/visas/visa/skilled-migrant-category-resident-visa", publisher: "Immigration New Zealand" }],
    lastReviewed: "2026-04-25",
    confidence: "seeded",
  },
  {
    id: "ie-critical-skills",
    countryId: "ireland",
    name: "Critical Skills Employment Permit to Stamp 4",
    category: "employer_sponsored",
    summary: "Employer-backed route that can lead to long-term residence permission.",
    prTimelineMonths: [24, 36],
    citizenshipTimelineYears: [6, 7],
    minSavingsUsd: 8000,
    minEducationLevel: "bachelors",
    minLanguageLevel: "advanced",
    idealAgeMax: null,
    familyFriendly: true,
    documents: ["Passport", "Employment contract", "Qualification evidence", "Role details", "Medical insurance", "Police certificate if requested"],
    eligibilityNotes: ["Role, salary, and occupation eligibility are key constraints."],
    sourceLinks: [{ title: "Critical Skills Employment Permit", url: "https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/permit-types/critical-skills-employment-permit/", publisher: "Department of Enterprise, Trade and Employment" }],
    lastReviewed: "2026-04-25",
    confidence: "seeded",
  },
  {
    id: "uk-skilled-worker",
    countryId: "united-kingdom",
    name: "Skilled Worker visa to ILR",
    category: "employer_sponsored",
    summary: "Employer-sponsored work route that may lead to settlement after qualifying residence.",
    prTimelineMonths: [60, 72],
    citizenshipTimelineYears: [6, 7],
    minSavingsUsd: 6000,
    minEducationLevel: null,
    minLanguageLevel: "intermediate",
    idealAgeMax: null,
    familyFriendly: true,
    documents: ["Passport", "Certificate of sponsorship", "English evidence", "Proof of funds if required", "Tuberculosis test if applicable"],
    eligibilityNotes: ["Requires a licensed sponsor and eligible role salary."],
    sourceLinks: [{ title: "Skilled Worker visa", url: "https://www.gov.uk/skilled-worker-visa", publisher: "UK Government" }],
    lastReviewed: "2026-04-25",
    confidence: "seeded",
  },
  {
    id: "de-skilled-worker",
    countryId: "germany",
    name: "Skilled Immigration Act route",
    category: "skilled_worker",
    summary: "Residence route for qualified professionals with recognized qualifications or relevant employment.",
    prTimelineMonths: [33, 60],
    citizenshipTimelineYears: [5, 8],
    minSavingsUsd: 9000,
    minEducationLevel: "diploma",
    minLanguageLevel: "intermediate",
    idealAgeMax: null,
    familyFriendly: true,
    documents: ["Passport", "Recognized qualification evidence", "Employment contract", "Proof of accommodation", "Health insurance", "Language evidence if needed"],
    eligibilityNotes: ["Qualification recognition and German language expectations vary by route."],
    sourceLinks: [{ title: "Visa for skilled workers", url: "https://www.make-it-in-germany.com/en/visa-residence/types/work-qualified-professionals", publisher: "Make it in Germany" }],
    lastReviewed: "2026-04-25",
    confidence: "seeded",
  },
  {
    id: "us-employment-green-card",
    countryId: "united-states",
    name: "H-1B to EB-2 or EB-3",
    category: "employer_sponsored",
    summary: "Employer-sponsored route that can lead from temporary work to a green card.",
    prTimelineMonths: [36, 120],
    citizenshipTimelineYears: [8, 14],
    minSavingsUsd: 20000,
    minEducationLevel: "bachelors",
    minLanguageLevel: "advanced",
    idealAgeMax: null,
    familyFriendly: true,
    documents: ["Passport", "Degree evidence", "Employer petition documents", "Labor certification materials", "Birth certificate", "Police or court records if applicable"],
    eligibilityNotes: ["Lottery, employer sponsorship, country backlogs, and role eligibility can make timelines uncertain."],
    sourceLinks: [{ title: "Green Card for Employment-Based Immigrants", url: "https://www.uscis.gov/green-card/green-card-eligibility/green-card-for-employment-based-immigrants", publisher: "USCIS" }],
    lastReviewed: "2026-04-25",
    confidence: "seeded",
  },
  {
    id: "mt-key-employee",
    countryId: "malta",
    name: "Key Employee Initiative",
    category: "employer_sponsored",
    summary: "Fast-track work permit route for highly skilled employees in Malta.",
    prTimelineMonths: [24, 60],
    citizenshipTimelineYears: [6, 8],
    minSavingsUsd: 10000,
    minEducationLevel: "bachelors",
    minLanguageLevel: "intermediate",
    idealAgeMax: null,
    familyFriendly: true,
    documents: ["Passport", "Employment contract", "Qualifications", "CV", "Health insurance", "Lease or accommodation evidence"],
    eligibilityNotes: ["Requires qualifying employment and salary conditions."],
    sourceLinks: [{ title: "Key Employee Initiative", url: "https://identita.gov.mt/central-visa-unit-key-employee-initiative/", publisher: "Identita Malta" }],
    lastReviewed: "2026-04-25",
    confidence: "seeded",
  },
];
